var docs = [
{path:"module/client.html", type:"class", title:"client.client", text:""},
{path:"class/MathematicalVector2.html", type:"class", title:"client.MathematicalVector2", text:""},
{path:"class/ColorSetting.html", type:"class", title:"client.ColorSetting", text:""},
{path:"class/Setting.html", type:"class", title:"client.Setting", text:""},
{path:"class/Module.html", type:"class", title:"client.Module", text:""},
{path:"class/VisualModule.html", type:"class", title:"client.VisualModule", text:""},
{path:"class/ScriptingModule.html", type:"class", title:"client.ScriptingModule", text:""},
{path:"class/Client_Settings.html", type:"class", title:"client_settings.Client_Settings", text:""},
{path:"class/Dimension.html", type:"class", title:"dimension.Dimension", text:""},
{path:"class/LightnessPair.html", type:"class", title:"dimension.LightnessPair", text:""},
{path:"class/Block.html", type:"class", title:"dimension.Block", text:""},
{path:"class/Biome.html", type:"class", title:"dimension.Biome", text:""},
{path:"class/event.html", type:"class", title:"events.event", text:""},
{path:"class/fs.html", type:"class", title:"fs.fs", text:""},
{path:"class/Stats.html", type:"class", title:"fs.Stats", text:""},
{path:"class/BinaryFile.html", type:"class", title:"fs.BinaryFile", text:""},
{path:"class/gfx.html", type:"class", title:"gfx.gfx", text:""},
{path:"class/gui.html", type:"class", title:"gui.gui", text:""},
{path:"class/iColor.html", type:"class", title:"gui.iColor", text:""},
{path:"class/Theme.html", type:"class", title:"gui.Theme", text:""},
{path:"class/Font.html", type:"class", title:"gui.Font", text:""},
{path:"class/player.html", type:"class", title:"player.player", text:""},
{path:"class/Effect.html", type:"class", title:"player.Effect", text:""},
{path:"class/AttributeListHolder.html", type:"class", title:"player.AttributeListHolder", text:""},
{path:"class/Attribute.html", type:"class", title:"player.Attribute", text:""},
{path:"class/Enchants.html", type:"class", title:"player.Enchants", text:""},
{path:"class/Item.html", type:"class", title:"player.Item", text:""},
{path:"class/InventoryArmor.html", type:"class", title:"player.InventoryArmor", text:""},
{path:"class/Inventory.html", type:"class", title:"player.Inventory", text:""},
{path:"class/server.html", type:"class", title:"server.server", text:""},
{path:"module/client.html", type:"module", title:"client", text:""},
{path:"module/dimension.html", type:"module", title:"dimension", text:""},
{path:"class/fs.html", type:"module", title:"fs", text:""},
{path:"module/globals.html", type:"module", title:"globals", text:""},
{path:"class/gui.html", type:"module", title:"gui", text:""},
{path:"class/player.html", type:"module", title:"player", text:""},
{path:"module/client.html#client.version", type:"field", title:"client.version", text:"string The client version"},
{path:"module/client.html#client.mcversion", type:"field", title:"client.mcversion", text:"string The minecraft version"},
{path:"class/MathematicalVector2.html#MathematicalVector2.x", type:"field", title:"MathematicalVector2.x", text:"number"},
{path:"class/MathematicalVector2.html#MathematicalVector2.y", type:"field", title:"MathematicalVector2.y", text:"number"},
{path:"class/ColorSetting.html#ColorSetting.r", type:"field", title:"ColorSetting.r", text:"number The amount of Red from a range of 0 to 1"},
{path:"class/ColorSetting.html#ColorSetting.g", type:"field", title:"ColorSetting.g", text:"number The amount of Green from a range of 0 to 1"},
{path:"class/ColorSetting.html#ColorSetting.b", type:"field", title:"ColorSetting.b", text:"number The amount of Blue from a range of 0 to 1"},
{path:"class/ColorSetting.html#ColorSetting.a", type:"field", title:"ColorSetting.a", text:"number The amount of Opacity from a range of 0 to 1"},
{path:"class/ColorSetting.html#ColorSetting.alphaVisible", type:"field", title:"ColorSetting.alphaVisible", text:"boolean alphaVisible Should the opacity slider be availible"},
{path:"class/ColorSetting.html#ColorSetting.rainbow", type:"field", title:"ColorSetting.rainbow", text:"boolean Is this color rainbow"},
{path:"class/ColorSetting.html#ColorSetting.rainbowSpeed", type:"field", title:"ColorSetting.rainbowSpeed", text:"number The speed of the rainbow effect (default=0.003)"},
{path:"class/Setting.html#Setting.type", type:"field", title:"Setting.type", text:"integer Types"},
{path:"class/Setting.html#Setting.name", type:"field", title:"Setting.name", text:"string The display name of the setting_type"},
{path:"class/Setting.html#Setting.saveName", type:"field", title:"Setting.saveName", text:"string The name used to save/load this Setting, no spaces"},
{path:"class/Setting.html#Setting.invisible", type:"field", title:"Setting.invisible", text:"boolean Should hide in the ui"},
{path:"class/Setting.html#Setting.value", type:"field", title:"Setting.value", text:"boolean|integer|number|MathematicalVector2|ColorSetting The value of the setting"},
{path:"class/Setting.html#Setting.default", type:"field", title:"Setting.default", text:"boolean|integer|number|MathematicalVector2|ColorSetting The default value of the setting"},
{path:"class/Setting.html#Setting.min", type:"field", title:"Setting.min", text:"integer|number|MathematicalVector2|nil Minimum value of the setting"},
{path:"class/Setting.html#Setting.max", type:"field", title:"Setting.max", text:"integer|number|MathematicalVector2|nil Maximum value of the setting"},
{path:"class/Module.html#Module.name", type:"field", title:"Module.name", text:"string The name of the module"},
{path:"class/Module.html#Module.description", type:"field", title:"Module.description", text:"string The description of the module"},
{path:"class/Module.html#Module.isVisual", type:"field", title:"Module.isVisual", text:"boolean if the module is a VisualModule"},
{path:"class/Module.html#Module.isScript", type:"field", title:"Module.isScript", text:"boolean if the module is a ScriptingModule"},
{path:"class/Module.html#Module.isvisibleingui", type:"field", title:"Module.isvisibleingui", text:"boolean if the module is visible in the clickgui"},
{path:"class/Module.html#Module.enabled", type:"field", title:"Module.enabled", text:"boolean [you can set] if the module is enabled"},
{path:"class/Module.html#Module.settings", type:"field", title:"Module.settings", text:"Setting[] A list with all the module's settings"},
{path:"class/VisualModule.html#VisualModule.size", type:"field", title:"VisualModule.size", text:"MathematicalVector2 The size of the module"},
{path:"class/VisualModule.html#VisualModule.pos", type:"field", title:"VisualModule.pos", text:"MathematicalVector2 The position of the module"},
{path:"class/VisualModule.html#VisualModule.relativepos", type:"field", title:"VisualModule.relativepos", text:"MathematicalVector2 The relative position of the module (relative from anchor position)"},
{path:"class/VisualModule.html#VisualModule.anchor", type:"field", title:"VisualModule.anchor", text:"0 = Invalid, 1 = Top Left, 2 = Top Right, 3 = Bottom Left, 4 = Bottom Right"},
{path:"class/ScriptingModule.html#ScriptingModule.movable", type:"field", title:"ScriptingModule.movable", text:"boolean If the module is movable"},
{path:"class/ScriptingModule.html#ScriptingModule.scale", type:"field", title:"ScriptingModule.scale", text:"number The scale of the module"},
{path:"class/ScriptingModule.html#ScriptingModule.size", type:"field", title:"ScriptingModule.size", text:"MathematicalVector2 The size of the module"},
{path:"class/ScriptingModule.html#ScriptingModule.pos", type:"field", title:"ScriptingModule.pos", text:"MathematicalVector2 The position of the module"},
{path:"class/LightnessPair.html#LightnessPair.blockLight", type:"field", title:"LightnessPair.blockLight", text:"integer The light level caused by torches and stuff"},
{path:"class/LightnessPair.html#LightnessPair.skyLight", type:"field", title:"LightnessPair.skyLight", text:"integer The light level of the environement (will not adapt to time)"},
{path:"class/Block.html#Block.id", type:"field", title:"Block.id", text:"integer The numerical identifier of the block (changes with versions)"},
{path:"class/Block.html#Block.data", type:"field", title:"Block.data", text:"integer The data of the block: exemple the color of the wool in a /setblock"},
{path:"class/Block.html#Block.name", type:"field", title:"Block.name", text:"string The name that would be used in /setblock"},
{path:"class/Block.html#Block.mapColor", type:"field", title:"Block.mapColor", text:"iColor The map color of the block"},
{path:"class/Biome.html#Biome.id", type:"field", title:"Biome.id", text:"integer The numerical identifier of the biome (might change with versions)"},
{path:"class/Biome.html#Biome.name", type:"field", title:"Biome.name", text:"string The name of the biome"},
{path:"class/Biome.html#Biome.temperature", type:"field", title:"Biome.temperature", text:"number The temperature of the biome"},
{path:"class/Biome.html#Biome.snow", type:"field", title:"Biome.snow", text:"boolean Can it snow in that biome"},
{path:"class/Biome.html#Biome.canRain", type:"field", title:"Biome.canRain", text:"boolean Can it rain in that biome"},
{path:"class/Stats.html#Stats.size", type:"field", title:"Stats.size", text:"integer Size of the file in bytes"},
{path:"class/Stats.html#Stats.readtime", type:"field", title:"Stats.readtime", text:"integer The last time the file was accessed (unix time)"},
{path:"class/Stats.html#Stats.writetime", type:"field", title:"Stats.writetime", text:"integer The last time the file was written to (unix time)"},
{path:"class/Stats.html#Stats.statustime", type:"field", title:"Stats.statustime", text:"integer The last time the file was accessed (unix time)"},
{path:"class/iColor.html#iColor.r", type:"field", title:"iColor.r", text:"integer"},
{path:"class/iColor.html#iColor.g", type:"field", title:"iColor.g", text:"integer"},
{path:"class/iColor.html#iColor.b", type:"field", title:"iColor.b", text:"integer"},
{path:"class/iColor.html#iColor.a", type:"field", title:"iColor.a", text:"integer"},
{path:"class/Theme.html#Theme.back", type:"field", title:"Theme.back", text:"iColor the background color, whats below everything"},
{path:"class/Theme.html#Theme.moduleOutline", type:"field", title:"Theme.moduleOutline", text:"iColor the outline of the visual modules in the hud editor"},
{path:"class/Theme.html#Theme.moduleOverlay", type:"field", title:"Theme.moduleOverlay", text:"iColor the overlay on top of the visual modules in the hud editor"},
{path:"class/Theme.html#Theme.darkbutton", type:"field", title:"Theme.darkbutton", text:"iColor most buttons use \"enabled\" but some use darkbutton's color instead"},
{path:"class/Theme.html#Theme.text", type:"field", title:"Theme.text", text:"iColor color of the text on the ui"},
{path:"class/Theme.html#Theme.largeArea", type:"field", title:"Theme.largeArea", text:"iColor color of the body of a window/pannel"},
{path:"class/Theme.html#Theme.titlebar", type:"field", title:"Theme.titlebar", text:"iColor color of the titlebar"},
{path:"class/Theme.html#Theme.disabled", type:"field", title:"Theme.disabled", text:"iColor color of disabled stuff"},
{path:"class/Theme.html#Theme.enabled", type:"field", title:"Theme.enabled", text:"iColor color of enabled stuff, can be used as accent color"},
{path:"class/Theme.html#Theme.blocked", type:"field", title:"Theme.blocked", text:"iColor blocked content in that color"},
{path:"class/Font.html#Font.isMinecrafttia", type:"field", title:"Font.isMinecrafttia", text:"boolean Is the minecraft blocky font in use"},
{path:"class/Font.html#Font.height", type:"field", title:"Font.height", text:"number the height of one char"},
{path:"class/Font.html#Font.wrap", type:"field", title:"Font.wrap", text:"number the height of one line"},
{path:"class/Effect.html#Effect.duration", type:"field", title:"Effect.duration", text:"number How long the effect will last in seconds"},
{path:"class/Effect.html#Effect.level", type:"field", title:"Effect.level", text:"integer How strong the effect will be: ex Strenght II"},
{path:"class/Effect.html#Effect.id", type:"field", title:"Effect.id", text:"integer The numerical identifier of the effect"},
{path:"class/Effect.html#Effect.effectTimeText", type:"field", title:"Effect.effectTimeText", text:"string The formated text of the time remaining (ex: 6:45)"},
{path:"class/Effect.html#Effect.name", type:"field", title:"Effect.name", text:"string The name of the effect ex: night_vision"},
{path:"class/Effect.html#Effect.vname", type:"field", title:"Effect.vname", text:"string The visual name ex: Night Vision II"},
{path:"class/AttributeListHolder.html#AttributeListHolder.size", type:"field", title:"AttributeListHolder.size", text:"integer"},
{path:"class/Attribute.html#Attribute.name", type:"field", title:"Attribute.name", text:"string The name of the attribute"},
{path:"class/Attribute.html#Attribute.id", type:"field", title:"Attribute.id", text:"integer The numerical identifier of the attribute"},
{path:"class/Attribute.html#Attribute.value", type:"field", title:"Attribute.value", text:"number The value of the attribute"},
{path:"class/Attribute.html#Attribute.default", type:"field", title:"Attribute.default", text:"number The default value of the attribute"},
{path:"class/Attribute.html#Attribute.min", type:"field", title:"Attribute.min", text:"number The minimum value of the attribute"},
{path:"class/Attribute.html#Attribute.max", type:"field", title:"Attribute.max", text:"number The maximum value of the attribute"},
{path:"class/Enchants.html#Enchants.id", type:"field", title:"Enchants.id", text:"integer The numerical identifier ex: 9"},
{path:"class/Enchants.html#Enchants.level", type:"field", title:"Enchants.level", text:"integer the level, ex: 1"},
{path:"class/Enchants.html#Enchants.name", type:"field", title:"Enchants.name", text:"string The name (like in /enchant) ex: sharpness"},
{path:"class/Item.html#Item.count", type:"field", title:"Item.count", text:"integer The amount of items in this stack"},
{path:"class/Item.html#Item.location", type:"field", title:"Item.location", text:"integer dont touch this dont guess it use it when referencing an item to client functions"},
{path:"class/Item.html#Item.id", type:"field", title:"Item.id", text:"integer The runtime numerical identifier of the item, will change often use for runtime only"},
{path:"class/Item.html#Item.blockid", type:"field", title:"Item.blockid", text:"integer The runtime numerical identifier of the block assosiated with the item, will change often use for runtime only"},
{path:"class/Item.html#Item.name", type:"field", title:"Item.name", text:"string The name of the item ex: diamond_sword"},
{path:"class/Item.html#Item.blockname", type:"field", title:"Item.blockname", text:"string The name of the block assosiated with the item ex: carrots"},
{path:"class/Item.html#Item.maxStackCount", type:"field", title:"Item.maxStackCount", text:"integer The maximum amount of this item that can be stacked"},
{path:"class/Item.html#Item.maxDamage", type:"field", title:"Item.maxDamage", text:"integer The maximum durability of an item"},
{path:"class/Item.html#Item.durability", type:"field", title:"Item.durability", text:"integer The amount of damage applied to that item"},
{path:"class/Item.html#Item.data", type:"field", title:"Item.data", text:"integer The data of the item, like in /give with dye and things like that"},
{path:"class/Item.html#Item.customName", type:"field", title:"Item.customName", text:"string The name (ex: from anvils)"},
{path:"class/Item.html#Item.enchant", type:"field", title:"Item.enchant", text:"Enchants[]"},
{path:"class/InventoryArmor.html#InventoryArmor.helmet", type:"field", title:"InventoryArmor.helmet", text:"Item|nil the item on the head"},
{path:"class/InventoryArmor.html#InventoryArmor.chestplace", type:"field", title:"InventoryArmor.chestplace", text:"Item|nil the item on the torso"},
{path:"class/InventoryArmor.html#InventoryArmor.leggings", type:"field", title:"InventoryArmor.leggings", text:"Item|nil the item on the legs"},
{path:"class/InventoryArmor.html#InventoryArmor.boots", type:"field", title:"InventoryArmor.boots", text:"Item|nil the item on the feets"},
{path:"class/Inventory.html#Inventory.size", type:"field", title:"Inventory.size", text:"integer The size of the inventory"},
{path:"class/Inventory.html#Inventory.selected", type:"field", title:"Inventory.selected", text:"integer The selected slot in the inventory (hotbar)"},
{path:"module/client.html#client.notification", type:"function", title:"client.notification", text:"Sends a client notification"},
{path:"module/client.html#client.execute", type:"function", title:"client.execute", text:"Executes a client command, do not include the prefix"},
{path:"class/ScriptingModule.html#client.modules", type:"function", title:"client.modules", text:"Gets a list of all the modules in the client"},
{path:"class/Client_Settings.html#client.settings.addAir", type:"function", title:"client.settings.addAir", text:"Adds a space in the ui"},
{path:"class/Client_Settings.html#client.settings.addInfo", type:"function", title:"client.settings.addInfo", text:"Adds text in the ui, you can change the content of the variable and the ui will display the changes"},
{path:"class/Client_Settings.html#client.settings.addBool", type:"function", title:"client.settings.addBool", text:"Adds a toggle switch in the ui"},
{path:"class/Client_Settings.html#client.settings.addKeybind", type:"function", title:"client.settings.addKeybind", text:"Adds a keybind for the user to set in the ui"},
{path:"class/Client_Settings.html#client.settings.addInt", type:"function", title:"client.settings.addInt", text:"Adds a slider in the ui"},
{path:"class/Client_Settings.html#client.settings.addFloat", type:"function", title:"client.settings.addFloat", text:"Adds a slider in the ui"},
{path:"class/Client_Settings.html#client.settings.addColor", type:"function", title:"client.settings.addColor", text:"Adds a color for the user to change in the ui"},
{path:"class/Client_Settings.html#client.settings.addFunction", type:"function", title:"client.settings.addFunction", text:"Adds a button in the ui"},
{path:"class/Client_Settings.html#client.settings.send", type:"function", title:"client.settings.send", text:"Sends setting value from the script to the client If you change one of the settings yourself it may not apply, this will make it apply"},
{path:"class/Client_Settings.html#client.settings.send", type:"function", title:"client.settings.send", text:"Sends setting value from the script to the client If you change one of the settings yourself it may not apply, this will make it apply"},
{path:"class/Client_Settings.html#client.settings.reload", type:"function", title:"client.settings.reload", text:"Gets the latest settings from the client Close to useless"},
{path:"class/Dimension.html#dimension.id", type:"function", title:"dimension.id", text:""},
{path:"class/Dimension.html#dimension.name", type:"function", title:"dimension.name", text:""},
{path:"class/Dimension.html#dimension.time", type:"function", title:"dimension.time", text:"The time in the dimension ranges from 0 to 1, 0 is the start of the day 0.5 is night and 1 is the end of the day will wrap to 0"},
{path:"class/Dimension.html#dimension.isRaining", type:"function", title:"dimension.isRaining", text:"Will return true if it is currently raining"},
{path:"class/Dimension.html#dimension.sound", type:"function", title:"dimension.sound", text:"Plays a sound at these coordinates"},
{path:"class/Biome.html#dimension.getBrightness", type:"function", title:"dimension.getBrightness", text:"Gets the light levels of these coordinates"},
{path:"class/Biome.html#dimension.getBlock", type:"function", title:"dimension.getBlock", text:"Gets the block at these coordinates"},
{path:"class/Biome.html#dimension.getBiome", type:"function", title:"dimension.getBiome", text:"Gets the biome at these coordinates"},
{path:"class/event.html#event.listen", type:"function", title:"event.listen", text:"Binds an event to a function"},
{path:"class/fs.html#fs.exist", type:"function", title:"fs.exist", text:"Checks if a file exist"},
{path:"class/fs.html#fs.isdir", type:"function", title:"fs.isdir", text:"Checks if a path is a directory"},
{path:"class/fs.html#fs.mkdir", type:"function", title:"fs.mkdir", text:"Creates a directory"},
{path:"class/fs.html#fs.delete", type:"function", title:"fs.delete", text:"Deletes a file"},
{path:"class/fs.html#fs.copy", type:"function", title:"fs.copy", text:"Copies a file"},
{path:"class/fs.html#fs.move", type:"function", title:"fs.move", text:"Moves a file"},
{path:"class/fs.html#fs.files", type:"function", title:"fs.files", text:"Give you a list of all files in a directory"},
{path:"class/fs.html#fs.directories", type:"function", title:"fs.directories", text:"Give you a list of all directories in a directory"},
{path:"class/Stats.html#fs.stats", type:"function", title:"fs.stats", text:"Gets information about a file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.close", type:"function", title:"_acp_BinaryFile:close", text:"Close the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.flush", type:"function", title:"_acp_BinaryFile:flush", text:"Flushes the buffer, Makes what you wrote to it actually go to disk without closing it"},
{path:"class/BinaryFile.html#_acp_BinaryFile.eof", type:"function", title:"_acp_BinaryFile:eof", text:"If the file has reach the end of the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.size", type:"function", title:"_acp_BinaryFile:size", text:"The size of the file in bytes (*not remaining bytes to read*)"},
{path:"class/BinaryFile.html#_acp_BinaryFile.seek", type:"function", title:"_acp_BinaryFile:seek", text:"Goes to a position in the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.tell", type:"function", title:"_acp_BinaryFile:tell", text:"The current position in the file (ex: reading from begin + 56)"},
{path:"class/BinaryFile.html#_acp_BinaryFile.write", type:"function", title:"_acp_BinaryFile:write", text:"Writes content to the file, make sure not to screw up the byteCount"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeByte", type:"function", title:"_acp_BinaryFile:writeByte", text:"Writes a byte to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeShort", type:"function", title:"_acp_BinaryFile:writeShort", text:"Writes a short to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeInt", type:"function", title:"_acp_BinaryFile:writeInt", text:"Writes an int to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeFloat", type:"function", title:"_acp_BinaryFile:writeFloat", text:"Writes a float to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeDouble", type:"function", title:"_acp_BinaryFile:writeDouble", text:"Writes a double to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.writeString", type:"function", title:"_acp_BinaryFile:writeString", text:"Writes Text to the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.read", type:"function", title:"_acp_BinaryFile:read", text:"Reads content from the file, make sure not to screw up the byteCount"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readByte", type:"function", title:"_acp_BinaryFile:readByte", text:"Reads a byte from the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readShort", type:"function", title:"_acp_BinaryFile:readShort", text:"Reads a short from the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readInt", type:"function", title:"_acp_BinaryFile:readInt", text:"Reads an int from the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readFloat", type:"function", title:"_acp_BinaryFile:readFloat", text:"Reads a float from the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readDouble", type:"function", title:"_acp_BinaryFile:readDouble", text:"Reads a double from the file"},
{path:"class/BinaryFile.html#_acp_BinaryFile.readString", type:"function", title:"_acp_BinaryFile:readString", text:"Reads Text from the file"},
{path:"class/BinaryFile.html#fs.open", type:"function", title:"fs.open", text:"Opens a file to read/write data"},
{path:"class/gfx.html#gfx.color", type:"function", title:"gfx.color", text:"Sets the drawing color, values range from 0 to 255"},
{path:"class/gfx.html#gfx.renderBehind", type:"function", title:"gfx.renderBehind", text:"Sets if the 3D rendering should render trough blocks"},
{path:"class/gfx.html#gfx.color", type:"function", title:"gfx.color", text:"Sets the drawing color, values range from 0 to 255"},
{path:"class/gfx.html#gfx.rect", type:"function", title:"gfx.rect", text:"Renders a rectangle"},
{path:"class/gfx.html#gfx.drawRect", type:"function", title:"gfx.drawRect", text:"Renders the outline of a rectangle"},
{path:"class/gfx.html#gfx.roundRect", type:"function", title:"gfx.roundRect", text:"Renders a rectangle with round in the corners"},
{path:"class/gfx.html#gfx.roundRectex", type:"function", title:"gfx.roundRectex", text:"Renders a rectangle with round in the corners or not"},
{path:"class/gfx.html#gfx.circle", type:"function", title:"gfx.circle", text:"Renders a circle"},
{path:"class/gfx.html#gfx.text", type:"function", title:"gfx.text", text:"Renders Text"},
{path:"class/gfx.html#gfx.text", type:"function", title:"gfx.text", text:"Renders Text"},
{path:"class/gfx.html#gfx.item", type:"function", title:"gfx.item", text:"Renders an Item"},
{path:"class/gfx.html#gfx.item", type:"function", title:"gfx.item", text:"Renders an Item"},
{path:"class/gfx.html#gfx.image", type:"function", title:"gfx.image", text:"Renders an Image"},
{path:"class/gfx.html#gfx.cimage", type:"function", title:"gfx.cimage", text:"Loads an Image, use gfx.fimage() to render it"},
{path:"class/gfx.html#gfx.texture", type:"function", title:"gfx.texture", text:"Renders a Texture (from the game)"},
{path:"class/gfx.html#gfx.ctexture", type:"function", title:"gfx.ctexture", text:"Loads a Texture (from the game) use gfx.fimage() to render it"},
{path:"class/gfx.html#gfx.fimage", type:"function", title:"gfx.fimage", text:"Renders loaded textures from gfx.ctexture() or gfx.cimage() (needs to come from the same file)"},
{path:"class/gfx.html#gfx.fimage", type:"function", title:"gfx.fimage", text:"Renders loaded textures from gfx.ctexture() or gfx.cimage() (needs to come from the same file)"},
{path:"class/gfx.html#gfx.cfimage", type:"function", title:"gfx.cfimage", text:"Renders loaded textures with colors from gfx.ctexture() or gfx.cimage() (needs to come from the same file)"},
{path:"class/gfx.html#gfx.unloadimage", type:"function", title:"gfx.unloadimage", text:"Unloads an image from memory"},
{path:"class/gfx.html#gfx.effect", type:"function", title:"gfx.effect", text:"Renders the icon of an effect"},
{path:"class/gfx.html#gfx.line", type:"function", title:"gfx.line", text:"Renders a line (2d, use in render)"},
{path:"class/gfx.html#gfx.line", type:"function", title:"gfx.line", text:"Renders a line (3d, use in render3d)"},
{path:"class/gfx.html#gfx.triangle", type:"function", title:"gfx.triangle", text:"Renders a triangle (2d, use in render)"},
{path:"class/gfx.html#gfx.triangle", type:"function", title:"gfx.triangle", text:"Renders a triangle (2d, use in render)"},
{path:"class/gfx.html#gfx.triangle", type:"function", title:"gfx.triangle", text:"Renders a triangle (3d, use in render3d)"},
{path:"class/gfx.html#gfx.triangle", type:"function", title:"gfx.triangle", text:"Renders a triangle (3d, use in render3d)"},
{path:"class/gfx.html#gfx.quad", type:"function", title:"gfx.quad", text:"Renders a quad (2d, use in render)"},
{path:"class/gfx.html#gfx.quad", type:"function", title:"gfx.quad", text:"Renders a quad (2d, use in render)"},
{path:"class/gfx.html#gfx.quad", type:"function", title:"gfx.quad", text:"Renders a quad (3d, use in render)"},
{path:"class/gfx.html#gfx.quad", type:"function", title:"gfx.quad", text:"Renders a quad (3d, use in render)"},
{path:"module/globals.html#globals.getClipboard", type:"function", title:"globals.getClipboard", text:"Gets the text from the clipboard"},
{path:"module/globals.html#globals.setClipboard", type:"function", title:"globals.setClipboard", text:"Sets the text in the clipboard"},
{path:"module/globals.html#globals.importLib", type:"function", title:"globals.importLib", text:"Executes a lua file from the Scripts/Libs folder"},
{path:"module/globals.html#globals.tableToJson", type:"function", title:"globals.tableToJson", text:"Executes a lua file from the Scripts/Libs folder"},
{path:"module/globals.html#globals.tableToJson", type:"function", title:"globals.tableToJson", text:"Executes a lua file from the Scripts/Libs folder"},
{path:"module/globals.html#globals.jsonToTable", type:"function", title:"globals.jsonToTable", text:"Executes a lua file from the Scripts/Libs folder"},
{path:"module/globals.html#globals.sendLocalData", type:"function", title:"globals.sendLocalData", text:"Sends data to all modules via the LocalDataReceived event You need to uniquely identify the messages that you want via the uuid"},
{path:"module/globals.html#globals.registerCommand", type:"function", title:"globals.registerCommand", text:"Allows you to make a command in a module You dont need a command file but it does not show in .help"},
{path:"module/globals.html#string.split", type:"function", title:"string.split", text:"Splits the string as expected"},
{path:"module/globals.html#globals.getItem", type:"function", title:"globals.getItem", text:"Gets an item from its name, you cannot render it tho as location is missing"},
{path:"class/gui.html#gui.width", type:"function", title:"gui.width", text:"The width of the screen"},
{path:"class/gui.html#gui.height", type:"function", title:"gui.height", text:"The height of the screen"},
{path:"class/gui.html#gui.scale", type:"function", title:"gui.scale", text:"The minecraft guiscale"},
{path:"class/gui.html#gui.mouseGrabbed", type:"function", title:"gui.mouseGrabbed", text:"If the user move the mouse it will affect the game or the ui (true = ui)"},
{path:"class/gui.html#gui.setGrab", type:"function", title:"gui.setGrab", text:"Set the mouseGrabbed state"},
{path:"class/gui.html#gui.mousex", type:"function", title:"gui.mousex", text:"The position of the mouse on the X axis (left to right)"},
{path:"class/gui.html#gui.mousey", type:"function", title:"gui.mousey", text:"The position of the mouse on the Y axis (left to right)"},
{path:"class/gui.html#gui.showScreen", type:"function", title:"gui.showScreen", text:"Opens a client screen, exemple \"HudEditor\""},
{path:"class/gui.html#gui.clickSound", type:"function", title:"gui.clickSound", text:"Plays the click sound (the one in minecraft when u clicc button)"},
{path:"class/gui.html#gui.sound", type:"function", title:"gui.sound", text:"Plays a sound on the ui (will not go away if you move)"},
{path:"class/gui.html#gui.stopallsound", type:"function", title:"gui.stopallsound", text:"Stops all sound that are playing"},
{path:"class/gui.html#gui.stopallsound", type:"function", title:"gui.stopallsound", text:"Stops all sound that are playing"},
{path:"class/gui.html#gui.theme", type:"function", title:"gui.theme", text:"Stops all sound that are playing"},
{path:"class/gui.html#gui.font", type:"function", title:"gui.font", text:"Stops all sound that are playing"},
{path:"class/Font.html#_acp_font.width", type:"function", title:"_acp_font.width", text:"Returns the size of the text"},
{path:"class/Font.html#_acp_font.width", type:"function", title:"_acp_font.width", text:"Returns the size of the text"},
{path:"class/player.html#player.gamemode", type:"function", title:"player.gamemode", text:"The current gamemode of the player"},
{path:"class/player.html#player.position", type:"function", title:"player.position", text:"The position of the player"},
{path:"class/player.html#player.selectedPos", type:"function", title:"player.selectedPos", text:"The coordinates of the block that has the outline for the player You can check if there is one in the first place with player.facingBlock()"},
{path:"class/player.html#player.lookingPos", type:"function", title:"player.lookingPos", text:"Where the raytrace hit, exemple: you look at a block far away, where on that block are you looking at"},
{path:"class/player.html#player.rotation", type:"function", title:"player.rotation", text:"Where the player looks at"},
{path:"class/player.html#player.facingEntity", type:"function", title:"player.facingEntity", text:"If the player were to left click would it attack an entity"},
{path:"class/player.html#player.facingBlock", type:"function", title:"player.facingBlock", text:"If the player were to left click would it attack a block"},
{path:"class/player.html#player.name", type:"function", title:"player.name", text:"The xbox pro gamering tag"},
{path:"class/player.html#player.nametag", type:"function", title:"player.nametag", text:"empty in vanilla, servers can set a custom nametag there"},
{path:"class/player.html#player.getFlag", type:"function", title:"player.getFlag", text:"Returns if true if the flag is true"},
{path:"class/Effect.html#player.effects", type:"function", title:"player.effects", text:""},
{path:"class/Attribute.html#_acp_AttributeListHolder.name", type:"function", title:"_acp_AttributeListHolder.name", text:"Gets the attribute with this name or nil"},
{path:"class/Attribute.html#_acp_AttributeListHolder.id", type:"function", title:"_acp_AttributeListHolder.id", text:"Gets the attribute with this id or nil"},
{path:"class/Attribute.html#_acp_AttributeListHolder.at", type:"function", title:"_acp_AttributeListHolder.at", text:"Gets the attribute at this position in the list or nil"},
{path:"class/Attribute.html#player.attributes", type:"function", title:"player.attributes", text:"Gets the attributes"},
{path:"class/Inventory.html#_acp_Inventory.armor", type:"function", title:"_acp_Inventory.armor", text:"The armor inventory"},
{path:"class/Inventory.html#_acp_Inventory.offhand", type:"function", title:"_acp_Inventory.offhand", text:"The item in the second hand"},
{path:"class/Inventory.html#_acp_Inventory.at", type:"function", title:"_acp_Inventory.at", text:"The item in slot or nil"},
{path:"class/Inventory.html#player.inventory", type:"function", title:"player.inventory", text:"Gets the inventory of the player"},
{path:"class/server.html#server.ipConnected", type:"function", title:"server.ipConnected", text:"The ip that you are currently exchanging packets with"},
{path:"class/server.html#server.ip", type:"function", title:"server.ip", text:"The ip that you used to join the server"},
{path:"class/server.html#server.port", type:"function", title:"server.port", text:"The port"},
{path:"class/server.html#server.worldName", type:"function", title:"server.worldName", text:"The name of the world (whats in top right in pause screen)"},
{path:"class/server.html#server.players", type:"function", title:"server.players", text:"The name of everyone in the pause menu"},
];